name: Deploy Backend to Elastic Beanstalk

on:
  push:
    branches:
      - main
      - backend  # Adjust this if you want to deploy from a different branch.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.11.1'

    - name: Install AWS CLI v2
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update   # Added --update flag to avoid reinstallation error

    - name: Log in to Amazon ECR
      env:
        AWS_REGION: us-west-2
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}  # Store AWS account ID in secrets
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

    - name: Build Docker image
      run: |
        docker build -t my-backend-app .

    - name: Tag Docker image
      env:
        AWS_REGION: us-west-2
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      run: |
        docker tag my-backend-app:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/my-backend-app:latest

    - name: Push Docker image to ECR
      env:
        AWS_REGION: us-west-2
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      run: |
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/my-backend-app:latest

    - name: Deploy to Elastic Beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-south-1  # Ensure this matches your desired AWS region
      run: |
        eb init -p docker my-backend-app --region $AWS_REGION
        eb use my-backend-app-env   # Ensure you're using the correct environment
        eb deploy my-backend-app-env