name: Deploy Backend to Docker Hub

on:
  push:
    branches:
      - main
      - backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t my-backend-app -f backend/Dockerfile backend

    - name: Log in to Docker Hub
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      run: |
        echo "$DOCKER_HUB_ACCESS_TOKEN" | docker login --username "$DOCKER_HUB_USERNAME" --password-stdin

    - name: Tag Docker image
      run: |
        docker tag my-backend-app:latest amarjha01/electramart:latest

    - name: Push Docker image to Docker Hub
      run: |
        docker push amarjha01/electramart:latest

    - name: Deploy to Elastic Beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-south-1
      run: |
        eb init -p docker my-backend-app --region $AWS_REGION
        eb use my-backend-app-env
        eb deploy my-backend-app-env
